// Official-flavor taxonomy — shared by the seed and the stats section.
// tagOf() maps a drink's name+flavor to one normalized flavor tag so we can
// aggregate "favorite flavors" across brands.

// display labels (RU)
export const FLAVOR_LABELS = {
  coffee: "Кофе",
  tea: "Чай",
  caramel: "Карамель",
  vanilla: "Ваниль",
  mango: "Манго",
  peach: "Персик",
  apricot: "Абрикос",
  cherry: "Вишня",
  blueberry: "Черника",
  cranberry: "Клюква",
  pomegranate: "Гранат",
  watermelon: "Арбуз",
  melon: "Дыня",
  pineapple: "Ананас",
  coconut: "Кокос",
  guava: "Гуава",
  strawberry: "Клубника",
  raspberry: "Малина",
  cactus: "Кактус",
  lychee: "Личи",
  barberry: "Барбарис",
  passion: "Маракуйя",
  apple: "Яблоко",
  kiwi: "Киви",
  feijoa: "Фейхоа",
  banana: "Банан",
  mojito: "Мохито",
  bubblegum: "Бабл-гам",
  marshmallow: "Маршмеллоу",
  cola: "Кола",
  lemonade: "Лимонад",
  orange: "Апельсин",
  citrus: "Цитрус",
  grape: "Виноград",
  tropical: "Тропик",
  multifruit: "Мультифрукт",
  berry: "Ягоды",
  zero: "Без сахара",
  original: "Оригинал",
  other: "Другое",
};

// ordered high→low priority; first group whose token appears wins
const GROUPS = [
  [
    "coffee",
    [
      "кофе",
      "coffee",
      "мокко",
      "moca",
      "эспрессо",
      "espresso",
      "латте",
      "капуч",
    ],
  ],
  ["tea", ["чай", "tea"]],
  ["caramel", ["карамель", "caramel"]],
  ["vanilla", ["ваниль", "vanilla"]],
  ["mango", ["манго", "mango"]],
  ["peach", ["персик", "peach", "нектарин", "nectar"]],
  ["apricot", ["абрикос", "apricot"]],
  ["cherry", ["вишн", "cherry", "черешн"]],
  ["blueberry", ["черник", "blueberry"]],
  ["cranberry", ["клюкв", "cranberry"]],
  ["pomegranate", ["гранат", "pomegranate"]],
  ["watermelon", ["арбуз", "watermelon"]],
  ["melon", ["дын", "melon"]],
  ["pineapple", ["ананас", "pineapple"]],
  ["coconut", ["кокос", "coconut"]],
  ["guava", ["гуава", "guava"]],
  ["strawberry", ["клубник", "strawberry"]],
  ["raspberry", ["малин", "raspberry", "razz"]],
  ["cactus", ["кактус", "cactus"]],
  ["lychee", ["личи", "lychee", "litchi"]],
  ["barberry", ["барбарис", "barberry"]],
  ["passion", ["маракуй", "passion", "pipeline"]],
  ["apple", ["яблок", "apple"]],
  ["kiwi", ["киви", "kiwi"]],
  ["feijoa", ["фейхоа", "feijoa"]],
  ["banana", ["банан", "banana"]],
  ["bubblegum", ["бабл", "bubble", "жвачк"]],
  ["marshmallow", ["маршмеллоу", "marshmallow", "зефир"]],
  ["mojito", ["мохито", "mojito", "мят", "mint"]],
  ["cola", ["кола", "cola"]],
  ["lemonade", ["лимонад", "lemonade"]],
  ["orange", ["апельсин", "orange", "sunrise", "dreamsicle"]],
  [
    "citrus",
    [
      "цитрус",
      "citrus",
      "лимон",
      "лайм",
      "lime",
      "грейпфрут",
      "лемонграсс",
      "lemongrass",
      "dew",
    ],
  ],
  ["grape", ["виноград", "grape"]],
  ["tropical", ["тропич", "тропик", "tropical", "tropic"]],
  [
    "multifruit",
    [
      "мультифрукт",
      "мультифрут",
      "сок",
      "микс",
      "multifruit",
      "пунш",
      "punch",
      "khaos",
      "хаос",
    ],
  ],
  ["berry", ["ягод", "berry", "лесн", "wildberry", "pacific"]],
  [
    "zero",
    [
      "без сахара",
      "zero",
      "ultra",
      "ультра",
      "sugarfree",
      "sugar free",
      "white",
    ],
  ],
  [
    "original",
    [
      "оригинал",
      "классик",
      "original",
      "classic",
      "energy",
      "ориджинал",
      "assault",
    ],
  ],
];

export function tagOf(text) {
  const t = String(text || "").toLowerCase();
  for (const [tag, toks] of GROUPS) {
    if (toks.some((tok) => t.includes(tok))) return tag;
  }
  return "other";
}
